# Generated by Django 5.2.10 on 2026-01-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('job_title', models.CharField(max_length=160)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('description', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
        ),
    ]
